const yup = require('../config/yup');

const editSchema = yup.object().shape({
  cnpj: yup.string().length(14),
  identificador_matriz_filial: yup.number().integer(),
  descricao_matriz_filial: yup.string(),
  razao_social: yup.string(),
  nome_fantasia: yup.string(),
  situacao_cadastral: yup.number().integer(),
  descricao_situacao_cadastral: yup.string(),
  data_situacao_cadastral: yup.string(),
  motivo_situacao_cadastral: yup.number().integer(),
  nome_cidade_exterior: yup.string(),
  codigo_natureza_juridica: yup.number().integer(),
  data_inicio_atividade: yup.string(),
  cnae_fiscal: yup.number().integer(),
  cnae_fiscal_descricao: yup.string(),
  descricao_tipo_logradouro: yup.string(),
  logradouro: yup.string(),
  numero: yup.string(),
  complemento: yup.string(),
  bairro: yup.string(),
  cep: yup.number().integer(),
  uf: yup.string().length(2),
  codigo_municipio: yup.number().integer(),
  municipio: yup.string(),
  ddd_telefone_1: yup.string(),
  ddd_telefone_2: yup.string(),
  ddd_fax: yup.string(),
  qualificacao_do_responsavel: yup.number().integer(),
  capital_social: yup.number().integer(),
  porte: yup.number().integer(),
  descricao_porte: yup.string(),
  opcao_pelo_simples: yup.boolean(),
  data_opcao_pelo_simples: yup.string(),
  data_exclusao_do_simples: yup.string(),
  opcao_pelo_mei: yup.boolean(),
  situacao_especial: yup.string(),
  data_situacao_especial: yup.string(),
});

module.exports = editSchema;
